### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by Brianxq** [ShiqiYu/libfacedetection.train#12]
How can I solve this probelm？ I'm using python3.6.5 torch 1.5.0+cuda92

**Comment by xchangfeng** [comment]
It's can not  working in windows system.

**Comment by fengyuentau** [comment]
The `resource`  module is Unix specific. You can try removing code related to `resource` if you want to train on non-Unix-based systems.

More details on https://docs.python.org/3/library/resource.html.
