### ISSUE TITLE
the bounding boxes are not same in dataset_rect and dataset_landmark

### ISSUE THREAD

**Issue by chenghan1995** [ShiqiYu/libfacedetection.train#15]
The bounding boxes are not same in dataset_rect and dataset_landmark, the face count in dataset_rect are larger than the one in dataset_landmark. Would tiny faces in dataset_landmark be seriously restrained during training?

**Comment by fengyuentau** [comment]
As for annotation, faces whose scale is less than 8 pixels is removed in both of the dataset. Some small faces whose landmarks are hard to be annotated are removed in `WIDER_Face_landmark`.

Scale is calculated as follows:
```python
import math
scale = math.sqrt(img_w * img_h)
```
