### ISSUE TITLE
和原始版本caffe模型的区别

### ISSUE THREAD

**Issue by fire717** [ShiqiYu/libfacedetection.train#18]
于老师您好，我之前跑过您开源的caffe模型（https://github.com/ShiqiYu/libfacedetection/tree/master/models/caffe/yufacedetectnet-open-v1.caffemodel）
，效果挺好的。

现在想重新训练，但是开源的是pytorch版本，所以想问：
1. 这个版本包括检测五个关键点，那么在推理时间上和之前的只检测人脸框的caffe模型有区别吗？
2. 如果有区别，那么我把模型修改去掉检测关键点，然后训练的模型转caffe，能否复现之前开源的caffe模型效果呢（速度和精度上）？

谢谢！

**Comment by ShiqiYu** [comment]
1. 没区别
2. 模型不同，v3模型更大一些，比v1准确率更高一点

**Comment by fire717** [comment]
> 1. 没区别
> 2. 模型不同，v3模型更大一些，比v1准确率更高一点

谢谢于老师解答，我最近在尝试用keras实现训练，后面训练完想对比下训练效果。
我看这个pytorch的训练annotation是包含了所有的训练集和验证集的，然后测试map是在验证集上进行，也就是说测试的数据在训练的时候用过，这样理解有问题吗？
再次感谢。

**Comment by fengyuentau** [comment]
> > 1. 没区别
> > 2. 模型不同，v3模型更大一些，比v1准确率更高一点
> 
> 谢谢于老师解答，我最近在尝试用keras实现训练，后面训练完想对比下训练效果。
> 我看这个pytorch的训练annotation是包含了所有的训练集和验证集的，然后测试map是在验证集上进行，也就是说测试的数据在训练的时候用过，这样理解有问题吗？
> 再次感谢。

@fire717 你好。
`$libfacedetection.train/data/WIDER_Face_rect/annotations`下包含了WIDER Face train和val的标注，但是训练的时候https://github.com/ShiqiYu/libfacedetection.train/blob/9ac244c3a332a7cc872c0d8b18d4dba781034f7c/tasks/task1/train.py#L104
https://github.com/ShiqiYu/libfacedetection.train/blob/9ac244c3a332a7cc872c0d8b18d4dba781034f7c/src/data.py#L293-L315
是从`$libfacedetection.train/data/WIDER_Face_rect/img_list.txt`中读取图片和标注文件的列表的，这个文件中所有的图片都是来自于WIDER Face train的。这个你可以自行验证一下。

因此，训练的数据并**没有包括WIDER Face的验证集**。
