### ISSUE TITLE
what is the comparison between normal face detection and this module

### ISSUE THREAD

**Issue by think-digvijay** [ShiqiYu/libfacedetection.train#21]

**Comment by fengyuentau** [comment]
This module is deep learning-based. Could you specify the meaning of "normal face detection"? If you mean the traditional face detector from OpenCV, it is built with handcrafted features (Haar-like features) and cascade structure.

**Comment by think-digvijay** [comment]
yess i got the point. i wanted to know about the architecture of your module

**Comment by fengyuentau** [comment]
The code of defining model structure is located in `YuFaceDetectNet` from https://github.com/ShiqiYu/libfacedetection.train/blob/master/tasks/task1/yufacedetectnet.py.
You can also refer to the visualization https://lutzroeder.github.io/netron/?url=https://raw.githubusercontent.com/ShiqiYu/libfacedetection.train/master/tasks/task1/onnx/facedetectcnn_320.onnx.
