### ISSUE TITLE
请问论文什么时候发表？

### ISSUE THREAD

**Issue by Krasjet-Yu** [ShiqiYu/libfacedetection.train#22]
在做实验的时候用到了您的代码，现在在写论文，怎么去引用您的文献？

**Comment by fengyuentau** [comment]
@zipYu 你好，目前请先引用我们这个项目的网址吧。

**Comment by fengyuentau** [comment]
https://github.com/ShiqiYu/libfacedetection.train#citation 欢迎引用我们的论文。
