### ISSUE TITLE
Will you release train codes for v3?

### ISSUE THREAD

**Issue by on-your-way** [ShiqiYu/libfacedetection.train#25]
Thanks for your great work!
The libfacedetection-v3 has many differences from v2, such as DSC and less width.
So will you release train codes for v3?

**Comment by fengyuentau** [comment]
We are sorting out the code. The code will be released soon.
To clarify, the current version released on libfacedetection is v3, while the current version of this repo is v2.

**Comment by on-your-way** [comment]
Thanks for reminding and look forward to v3.

**Comment by fengyuentau** [comment]
Code has been updated.
