### ISSUE TITLE
new annotation format

### ISSUE THREAD

**Issue by nhatanhphung** [ShiqiYu/libfacedetection.train#26]
Hello, I would like to ask how the new annotation txt file is written. From my understanding, 1st line is file name, 2nd line is number of faces, however 3rd/4th lines have 15 numbers, the last number i assume is visibility or opacity, however I do not know what the 14 other numbers represent because I assumed it was 5 facial landmarks thus 10 points.

Thank you

**Comment by fengyuentau** [comment]
There are some comments in `src/data.py`:
https://github.com/ShiqiYu/libfacedetection.train/blob/e72b34b26763538d7be1b75f9df498b30dd237b1/src/data.py#L311-L320

`(x1, y1)` is the top-left point of a bounding box. `lm` stands for landmarks.
