### ISSUE TITLE
GPU利用率低

### ISSUE THREAD

**Issue by sunny-sjj** [ShiqiYu/libfacedetection.train#27]
为什么我训练的时候利用率很低呢，我的cuda环境也配置好了

**Comment by fengyuentau** [comment]
目前I/O方面效率比较低，我们正在处理这个问题。其次模型也比较小，综合导致利用率较低。
训练时添加`OMP_NUM_THREADS=2`可提升训练速度，即`OMP_NUM_THREADS=2 python train.py`。>=2也可以。

**Comment by sunny-sjj** [comment]
嗯嗯，好的，谢谢

**Comment by sunny-sjj** [comment]
我还有个问题想问一下您。在您提供的multibox_loss.py的文件内，在计算eiou_loss的时候：   loc_t这个是不是没有给他分配target的值啊。还是我理解的有问题。

**Comment by fengyuentau** [comment]
https://github.com/ShiqiYu/libfacedetection.train/blob/e72b34b26763538d7be1b75f9df498b30dd237b1/src/multibox_loss.py#L89

这一行的`loc_p`是网络的预测值，`loc_t`是真实标签。我们用eiou来计算预测框与真实框之间的距离。

**Comment by sunny-sjj** [comment]
嗯嗯，是的。我理解的是loc_t应该等于这里的truths，但是我在代码中没有看到赋值操作
https://github.com/ShiqiYu/libfacedetection.train/blob/e72b34b26763538d7be1b75f9df498b30dd237b1/src/multibox_loss.py#L71

在代码中local_t只在这里赋值
https://github.com/ShiqiYu/libfacedetection.train/blob/e72b34b26763538d7be1b75f9df498b30dd237b1/src/multibox_loss.py#L67
请问是我的理解有问题吗？谢谢回复

**Comment by fengyuentau** [comment]
https://github.com/ShiqiYu/libfacedetection.train/blob/e72b34b26763538d7be1b75f9df498b30dd237b1/src/multibox_loss.py#L66-L75

第74行的match函数负责将anchor和gt匹配，匹配的gt会写入到`loc_t`里面（第148行）：
https://github.com/ShiqiYu/libfacedetection.train/blob/e72b34b26763538d7be1b75f9df498b30dd237b1/src/utils.py#L98-L151

**Comment by sunny-sjj** [comment]
啊啊啊，原来藏在这里，非常感谢您的回复。
