### ISSUE TITLE
only 1024 is supported?我想在100x100的图片上训练，应该怎么办呢？

### ISSUE THREAD

**Issue by kevinkinking** [ShiqiYu/libfacedetection.train#36]

**Comment by fengyuentau** [comment]
[这一行代码](https://github.com/ShiqiYu/libfacedetection.train/blob/74f3aa77c63234dd954d21286e9a60703b8d0868/tasks/task1/train.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L66)的注释并非是实际代码实现。

如果我没记错的话，我们的训练代码只是最后会图片把尺寸resize到320x320，对于图片实际尺寸无要求。那么您需要修改的地方就只有：
- 根据https://github.com/ShiqiYu/libfacedetection.train/blob/master/src/data.py ，生成coco格式的训练数据。
