### ISSUE TITLE
请问余老师，我看源码，图片在送入网络前会转成27通道，我需要训练单通道的图片，应该怎么修改呢

### ISSUE THREAD

**Issue by kevinkinking** [ShiqiYu/libfacedetection.train#37]
//only 27 elements used for each pixel
        create((imgHeight+1)/2, (imgWidth+1)/2, 32);
        //since the pixel assignment cannot fill all the elements in the blob.
        //some elements in the blob should be initialized to 0
        setZero();

**Comment by Wwupup** [comment]
Hello, the 27 channels you mentioned are implemented in C++to facilitate the conversion of 3x3 convolution calculation to 1x1 convolution calculation. Not related to the training program. If you want to train single channel pictures, you can change the input channel of head from 3 to 1 of the `conv_head`.

**Comment by zaidao2023** [comment]
> 您好，您提到的 27 个通道都是在 C++ 中实现的，以促进 3x3 卷积计算到 1x1 卷积计算的转换。与培训计划无关。如果要训练单通道图片，可以将头部的输入通道从 3 个更改为 1 个。`conv_head`

如果训练单通道图像完成，怎么转换模型到cpp里面？需要改哪些参数么

**Comment by Wwupup** [comment]
@zaidao2023 你好，以下代码是用于导出首层卷积的，如果修改为单通道图像输入可以尝试修改这部分：https://github.com/ShiqiYu/libfacedetection.train/blob/02246e79b1e976c83d1e135a85e0628120c93769/tools/yunet2cpp.py#L60-L68
同时，由于输入维度改变，还要修改C++首层实现：
https://github.com/ShiqiYu/libfacedetection/blob/26afabbfb8ae3e910112c77def258328a6975744/src/facedetectcnn.cpp#L82-L125

实际上，想应用单通道图像还有一种最简单的做法，即在预处理时将单通道图像[h, w, 1] repeat到[h, w, 3]适应本项目即可。

**Comment by zaidao2023** [comment]
> @zaidao2023 你好，以下代码是用于导出首层卷积的，如果修改为单通道图像输入可以尝试修改这部分：
> 
> https://github.com/ShiqiYu/libfacedetection.train/blob/02246e79b1e976c83d1e135a85e0628120c93769/tools/yunet2cpp.py#L60-L68
> 
> 
> 同时，由于输入维度改变，还要修改C++首层实现：
> https://github.com/ShiqiYu/libfacedetection/blob/26afabbfb8ae3e910112c77def258328a6975744/src/facedetectcnn.cpp#L82-L125
> 实际上，想应用单通道图像还有一种最简单的做法，即在预处理时将单通道图像[h, w, 1] repeat到[h, w, 3]适应本项目即可。

谢谢答复
