### ISSUE TITLE
Hello, can you write this code for training in C ++?

### ISSUE THREAD

**Issue by problemSolvingProgramming** [ShiqiYu/libfacedetection.train#42]
Hello, can you write this code for training in C ++?

https://github.com/ShiqiYu/libfacedetection.train

**Comment by ShiqiYu** [comment]
OMG!

**Comment by problemSolvingProgramming** [comment]
@ShiqiYu  My goal is to use your code for face recognition but I do not know exactly what to do for train?

**Comment by fengyuentau** [comment]
Face recognition and face detection are different tasks of different training schemes, and this repo is for face detection.

BTW, most of training code for deep learning models is based on Python.
