### ISSUE TITLE
 can't find from .bbox import 

### ISSUE THREAD

**Issue by xingjunhong** [ShiqiYu/libfacedetection.train#47]

**Comment by xingjunhong** [comment]
file:///home/xjh/%E5%9B%BE%E7%89%87/2022-07-15%2015-10-55%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png
file:///home/xjh/%E5%9B%BE%E7%89%87/2022-07-15%2015-12-16%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png
file:///home/xjh/%E5%9B%BE%E7%89%87/2022-07-15%2015-13-21%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png
file:///home/xjh/%E5%9B%BE%E7%89%87/2022-07-15%2015-10-55%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png
file:///home/xjh/%E5%9B%BE%E7%89%87/2022-07-15%2015-12-16%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png
file:///home/xjh/%E5%9B%BE%E7%89%87/2022-07-15%2015-13-21%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png
file:///home/xjh/%E5%9B%BE%E7%89%87/2022-07-15%2015-10-55%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png
file:///home/xjh/%E5%9B%BE%E7%89%87/2022-07-15%2015-12-16%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png
file:///home/xjh/%E5%9B%BE%E7%89%87/2022-07-15%2015-13-21%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png

**Comment by xingjunhong** [comment]
![1](https://user-images.githubusercontent.com/68151424/179173386-ddaa0bd8-0657-4e48-add6-2410168005d6.png)
![2](https://user-images.githubusercontent.com/68151424/179173393-61d5b692-cdef-4967-9023-930987faf5c6.png)
![3](https://user-images.githubusercontent.com/68151424/179173397-6158a3b7-92ac-4d65-b20f-ff04b4b7731d.png)
这是我的环境，为什么我的代码是红色的？还有.bbox？  
from .bbox import bbox_overlaps
希望能得到回复谢谢~

**Comment by fengyuentau** [comment]
这里有使用指南 https://github.com/ShiqiYu/libfacedetection.train#evaluation-on-wider-face

**Comment by xingjunhong** [comment]
问题已解决，非常感谢

**Comment by xingjunhong** [comment]
想问一下，模型训练后模型保存在哪里？
