### ISSUE TITLE
请问有拉流摄像头实时检测的代码吗？

### ISSUE THREAD

**Issue by xingjunhong** [ShiqiYu/libfacedetection.train#48]
看到detect.py 只有图片和视频的，但是为尝试过拉流摄像头实时检测，发现不行，请问有相应的代码可以提供下吗？
谢谢，希望能够得到回复

**Comment by fengyuentau** [comment]
这里有例子 https://github.com/opencv/opencv_zoo/blob/54190541bb9f717144b255358ca6b37e3e47bf23/models/face_detection_yunet/demo.py#L111-L136

**Comment by xingjunhong** [comment]
这里的yunet 和你给的例子里面的yunet不相同，我用哪一个呢？

**Comment by xingjunhong** [comment]
好的，谢谢，用的是onnx模型还是pth模型？

**Comment by fengyuentau** [comment]
这个仓库仅提供了pth的例子，链接内是onn×的例子

**Comment by xingjunhong** [comment]
好的，非常感谢，期待您的更新～
