### ISSUE TITLE
模型为640x640,转onnx输入尺寸不同，没有报错是什么原因？

### ISSUE THREAD

**Issue by xingjunhong** [ShiqiYu/libfacedetection.train#50]
模型为640x640，但是为转onnx的时候尺寸改为641的大小也一样可以转onnx，请问这是为什么呢？不是规定了是640x640的大小吗？

**Comment by xingjunhong** [comment]
我尝试了以下转onnx大小为（480，640）的，一样可以转，但模型是640x640的，想问一下这原因是什么？

**Comment by fengyuentau** [comment]
没看明白你的问题，可以附上代码说明你的问题吗？

**Comment by xingjunhong** [comment]
我想问一下，该工程有进行后处理吗？

**Comment by fengyuentau** [comment]
需要nms等后处理
________________________________
发件人: xingjunhong ***@***.***>
发送时间: Friday, July 22, 2022 7:39:58 PM
收件人: ShiqiYu/libfacedetection.train ***@***.***>
抄送: Yuantao Feng ***@***.***>; Comment ***@***.***>
主题: Re: [ShiqiYu/libfacedetection.train] 模型为640x640,转onnx输入尺寸不同，没有报错是什么原因？ (Issue #50)


我想问一下，该工程有进行后处理吗？

―

**Comment by xingjunhong** [comment]
代码位置可以说一下吗？我没有找到～谢谢你啦

**Comment by fengyuentau** [comment]
onnx推理的代码在libfacedetection/opencv_dnn里：https://github.com/ShiqiYu/libfacedetection/tree/master/opencv_dnn

**Comment by xingjunhong** [comment]
> onnx推理的代码在libfacedetection/opencv_dnn里：https://github.com/ShiqiYu/libfacedetection/tree/master/opencv_dnn

请问有c++的nms后处理代码吗？

**Comment by fengyuentau** [comment]
> 请问有c++的nms后处理代码吗？

可以参考这里：https://github.com/opencv/opencv/blob/3456d28cc2d52989f6a8d05ffb35765b6cbbb028/modules/objdetect/src/face_detect.cpp#L178-L267

**Comment by fengyuentau** [comment]
onnx推理的代码在libfacedetection仓库的opencv_dnn里面
________________________________
发件人: xingjunhong ***@***.***>
发送时间: Friday, July 22, 2022 7:46:03 PM
收件人: ShiqiYu/libfacedetection.train ***@***.***>
抄送: Yuantao Feng ***@***.***>; Comment ***@***.***>
主题: Re: [ShiqiYu/libfacedetection.train] 模型为640x640,转onnx输入尺寸不同，没有报错是什么原因？ (Issue #50)


代码位置可以说一下吗？我没有找到～谢谢你啦

―
