### ISSUE TITLE
[Docs] Visualization of network architecture points to older onnx file link

### ISSUE THREAD

**Issue by kishore-s-15** [ShiqiYu/libfacedetection.train#51]
**Issue:**

[Link](https://netron.app/?url=https://raw.githubusercontent.com/ShiqiYu/libfacedetection.train/master/tasks/task1/onnx/YuFaceDetectNet.onnx) for visualization of YuNet architecture from the README file does not point to the correct onnx file. The current link points to the onnx file based on the previous directory structure.

**Screenshot:**

![libfacedetection_readme_issue](https://user-images.githubusercontent.com/56688194/184377583-6815ac72-11f7-4a60-a2b6-392779b49790.png)

**Possible Fix:**

Have to update the README file to point to the latest onnx file (From the 3 onnx files currently present).

Can I work on it and raise a PR ?

**Comment by fengyuentau** [comment]
Yes, we welcome pull requests.

**Comment by kishore-s-15** [comment]
@fengyuentau Sure, I'll work on it. Out of the three model available [here](https://github.com/ShiqiYu/libfacedetection.train/tree/master/onnx). Which one do you want me to link or can I add all the three models to the README ?

**Comment by fengyuentau** [comment]
I would say the dynamic one is better for presenting. No need to list them all.

**Comment by kishore-s-15** [comment]
> I would say the dynamic one is better for presenting. No need to list them all.

Thanks, I'll add that model's link then.
