### ISSUE TITLE
May I ask do you still provide the training code for the model published at opencv github repo?

### ISSUE THREAD

**Issue by tsangz189** [ShiqiYu/libfacedetection.train#53]
Currently, I have some problems converting the model trained by this repo, but successfully convert the model at the OpenCV GitHub [repo](https://github.com/opencv/opencv_zoo/tree/master/models/face_detection_yunet).
So I wonder if the training code is still around?

**Comment by fengyuentau** [comment]
We update the model with code changes. So you can have a look at previous commits to find the corresponding training code for the previous models.
