### ISSUE TITLE
can not export to onnx

### ISSUE THREAD

**Issue by yonglianglan** [ShiqiYu/libfacedetection.train#63]
尝试通过python tools/yunet2onnx.py ./configs/yunet_n.py ./weights/yunet_n.pth 进行onnx转换，发现转换失败，我的mmcv安装版本是1.6

![image](https://user-images.githubusercontent.com/37431477/204716139-b9567d37-bd6b-4b0c-9d0f-a6b36fcf93f2.png)

**Comment by fengyuentau** [comment]
@Wwupup Please take a look at the problem.

**Comment by Wwupup** [comment]
Hello @yonglianglan, you can change the all `cfg.test_pipeline` to `cfg.data.test.pipeline` to avoid this error. And I have fix this bug in the new PR and you can easily `git fetch`.
