### ISSUE TITLE
当转onnx的时候，验证pytorch模型推理和onnx推理时候出现问题

### ISSUE THREAD

**Issue by yonglianglan** [ShiqiYu/libfacedetection.train#66]
python tools/yunet2onnx.py ./configs/yunet_n.py ./weights/yunet_n.pth --verify true
当转onnx的时候，验证pytorch模型推理和onnx推理时候出现问题。
![image](https://user-images.githubusercontent.com/37431477/205229622-d9277238-d734-4fed-911f-17e40229a36d.png)

**Comment by Wwupup** [comment]
@yonglianglan 已在最新的PR中修复该BUG。
