### ISSUE TITLE
Cannot download labelsv2

### ISSUE THREAD

**Issue by AlessandroMondin** [ShiqiYu/libfacedetection.train#69]
Hello!
I followed the suggested [link](https://share.weiyun.com/lRipUkSB)  to download "labelsv2" but after inserting the suggested password I cannot directly download the file because I am required some action with the QR-code (I don't speak Chinese)
What should I do?

**Comment by Wwupup** [comment]
@AlessandroMondin Hello, you can download this file in [link](https://drive.google.com/file/d/1DX9u07UbXDVJ91RFsLxR7eyUvs6_0crm/view?usp=sharing).

**Comment by AlessandroMondin** [comment]
Thanks a lot! Solved
