### ISSUE TITLE
nonsquare input size training and exporting

### ISSUE THREAD

**Issue by jimkuo2** [ShiqiYu/libfacedetection.train#73]
I firstly used my custom dataset and trained a model. Since I use the config yunet_n.py, all 'img_scale' and 'size' are (640, 640); but the input_shape of my exported onnx file is (1, 3, 736, 1280). I successfully convert this onnx file to tensorrt engine and get recall 83% on my own testing set.

However, all my custom dataset and testing set are formed of (height, width) = (720, 1080) or (1080, 1920) pictures. Hence I thought maybe I should adjust all 'img_scale' and 'size' to (736, 1280) in order to get a better model for my task.

Unfortunately, the model which trained with size (736, 1280) only get recall 50%, I also trained two models with size (1280, 1280) and (352, 640), and only get recall 70% and 50%. (all the input_shape of exported onnx files are (1, 3, 736, 1280))

Did I ignore somewhere also need to be adjusted if I don't want to use default size = (640, 640)?
The ordering of 'img_scale' and 'size' in the config and the the ordering of flag 'shape' in yunet2onnx.py are all (height, width), right?

**Comment by Wwupup** [comment]
Hello@jimkuo2 , sorry for the late reply. If you want to improve the detection performance of large-scale images, you can increase the range of RandomCrop, for example, change the original [0.3, 0.45, 0.6, 0.8, 1.0] to [0.5, 0.7, 0.9, 1.0, 1.2, 1.4, 1.6], without having to modify the input size during training.
