### ISSUE TITLE
How to find requirements.txt?

### ISSUE THREAD

**Issue by HongzeTian** [ShiqiYu/libfacedetection.train#8]
Hi Mr Yu,

How can I find the requirements.txt file?

**Comment by CathyRong** [comment]
> 
> 
> Hi Mr Yu,
> 
> How can I find the requirements.txt file?

same question

**Comment by VisImage** [comment]
The same question.

**Comment by VisImage** [comment]
> > Hi Mr Yu,
> > How can I find the requirements.txt file?
> 
> same question

The same question.

**Comment by ShiqiYu** [comment]
I will fix it soon. Anyway, you can install pytorch by yourself and skip this step.

**Comment by VisImage** [comment]
Thank you, I’ll try it further.

 

 

Dr. Shi Yin

CEO, VisImage Systems Inc.

30-70 East beaver creak road,

Richmond Hill, ON

L4B3B2, Canada

 <http://esfsecev-ty3014> www.vis.ca

**Comment by HongzeTian** [comment]
Thanks, Prof. One more question, it seems there is one file lacking in the data folder. 
`from .face_rect_landmark import FaceRectLMDataset, detection_collate`


> I will fix it soon. Anyway, you can install pytorch by yourself and skip this step.

**Comment by fengyuentau** [comment]
> Thanks, Prof. One more question, it seems there is one file lacking in the data folder.
> `from .face_rect_landmark import FaceRectLMDataset, detection_collate`
> 
> > I will fix it soon. Anyway, you can install pytorch by yourself and skip this step.

@HongzeTian These two classes are actually located in `$libfacedetection.train/src/data.py`.
