### ISSUE TITLE
how to convert pytorch model to openvino model ?

### ISSUE THREAD

**Issue by verigle** [ShiqiYu/libfacedetection.train#9]
how to convert pytorch model to openvino model?

**Comment by vladkol** [comment]
There is now [ONNX conversion script](https://github.com/ShiqiYu/libfacedetection.train/blob/master/tasks/task1/exportonnx.py) and 2 versions of the model [converted](https://github.com/ShiqiYu/libfacedetection.train/tree/master/tasks/task1/onnx). 
You can convert it using [OpenVINO toolkit](https://docs.openvinotoolkit.org/2020.1/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html#Convert_From_ONNX).
